name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app
        run: |
          xcodebuild \
          -scheme Settings \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          build

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r build/Release-iphoneos/Settings.app Payload/
          zip -r Settings.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Settings-IPA
          path: Settings.ipa